# These are some basics codes of using NumPy

In [1]:
import numpy as np

In [2]:
myarr=np.array([[1,2,3,4,5]])

In [3]:
myarr

array([[1, 2, 3, 4, 5]])

In [4]:
myarr[0]

array([1, 2, 3, 4, 5])

In [5]:
myarr[0,1]

2

In [6]:
myarr[0,1]=9

In [7]:
myarr

array([[1, 9, 3, 4, 5]])

In [9]:
myarr.shape

(1, 5)

In [13]:
myarray2=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [14]:
myarray2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
myarray2.shape

(3, 3)

In [16]:
myarray2.size

9

In [20]:
zeros=np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
linspace=np.linspace(1,5,12)
linspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [2]:
import numpy as np



In [4]:
rng=np.arange(99)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [13]:
rng=rng.reshape(3,33) 
rng

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [19]:
rng.shape

(3, 33)

In [24]:
rng=rng.ravel()
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
rng.shape

(99,)

In [27]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [28]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
#this will give you the sum for columns
ar.sum(axis=0)


array([12, 15, 18])

In [32]:
#this will give you the sum of rows
ar.sum(axis=1)

array([ 6, 15, 24])

In [33]:
#this will take a transpose of the gic=ven matrix
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
ar.flat

In [37]:
#this will print all the integers from the metix
for item in ar.flat:
    print (item)

1
2
3
4
5
6
7
8
9


In [38]:
#this will show you the dimentions of your array
ar.ndim

2

In [39]:
#this will show how much storage is your array taking
ar.nbytes

36

In [45]:
one=np.array([1,2,3,9,5,6])

In [46]:
one

array([1, 2, 3, 9, 5, 6])

In [47]:
#this will show you the maximum value in the array by marking indexes
one.argmax()

3

In [48]:
one.argmin()

0

In [53]:
#this will show you indexes to sort
one.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
ar.argmax()

8

In [52]:
ar.argmin()

0

In [54]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [56]:
ar2=[[2,3,4],[5,2,1],[3,5,3]]

In [60]:
ar2=np.array(ar2)

In [78]:
ar

(array([0], dtype=int64),)

In [61]:
ar2

array([[2, 3, 4],
       [5, 2, 1],
       [3, 5, 3]])

In [66]:
#some basic mathematical function using NumPy
a=ar+ar2
a

array([[ 3,  5,  7],
       [ 9,  7,  7],
       [10, 13, 12]])

In [67]:
m=ar*ar2
m

array([[ 2,  6, 12],
       [20, 10,  6],
       [21, 40, 27]])

In [68]:
m.T

array([[ 2, 20, 21],
       [ 6, 10, 40],
       [12,  6, 27]])

In [69]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [77]:
ar2

array([[2, 3, 4],
       [5, 2, 1],
       [3, 5, 3]])

In [81]:
np.where(ar2>4)

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))